http://merkel.zoneo.net/Latex/natbib.php

|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| \usepackage    | bibtex             | natbib             | biblatex                      | in line example authoryear         | numbered          |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| Backend        | bibtex             | bibtex             | biber                         |                                    |                   |
| Add .bib       | \bibliography{}    | \bibliography{}    | \addbibresource{}             |                                    |                   |
| Print Bib      | \bibliographystyle | \bibliographystyle | [style=citestyle+bibstyle]    |                                    |                   |
|                |                    |                    | \printbibliography            |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| to bibtex      | \cite              |                    | \cite                         | \citeX{jon90}                      |                   |
| to natbib      | \let\cite\citep    | \citep             | natbib=true                   |                                    |                   |
| to biblatex    | \let\cite\autocite |                    |                               |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| textual        | \cite              | \citet             | \textcite    \cite            | Jones et al. (1990)                | Jones et al. [21] |
| full authors   |                    | \citet*            |                               | Jones, Baker, and Williams (1990)  |                   |
|                |                    | \citealt           |                               | Jones et al. 1990                  |                   |
|                |                    | \citealt*          |                               | Jones, Baker, and Williams 1990    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| parenthetical  |                    | \citep             | \autocite    \parencite       | (Jones et al., 1990)               | [21]              |
|                |                    | \citep*            |                               | (Jones, Baker, and Williams, 1990) |                   |
|                |                    | \citealp           |                               | Jones et al., 1990                 |                   |
|                |                    | \citealp*          |                               | Jones, Baker, and Williams, 1990   |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| authoryear     |                    | \citeauthor        |                               | Jones et al.                       |                   |
|                |                    | \citeauthor*       |                               | Jones, Baker, and Williams         |                   |
|                |                    | \citeyear          |                               | 1990                               |                   |
|                |                    | \citeyearpar       |                               | (1990)                             |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| \defcitealias  |                    | \citetalias        |                               | Paper1                             |                   |
|                |                    | \citepalias        |                               | (Paper1)                           |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| chapterbib     |                    |                    | refsection=chapter            |                                    |                   |
| bibentry       | \bibentry          | \bibentry          | \fullcite                     |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| numeric style  | plain              | plainat            | style=numeric                 |                                    | ieeetr, acm, mdpi |
| square bracket | unsrt              |                    | style=numeric,sorting=none    |                                    |                   |
| [1]            | abbrv              | abbrvnat           | style=numeric,firstinits=true |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| alpha style    | alpha              |                    | style=alphabetic              |                                    |                   |
| [Tian14]       |                    |                    | biblatex-apa                  |                                    |                   |
| square bracket |                    |                    | amnat                         |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| authoryear...  |                    |                    | style=authoryear,apa,         | sorting=nty nty, nyvt, ydnt,none   | apalike           |
| (Tian and      |                    |                    |                               | year, name, volume, title.         |                   |
| Wang, 2014)    |                    |                    |                               | descending                         |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
| authortitle    |                    |                    | \footcite                     |                                    |                   |
|----------------+--------------------+--------------------+-------------------------------+------------------------------------+-------------------|
http://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib
%\printbibliography[heading=subbibintoc]  % subbib of each chapter in toc
%\printbibliography[heading=bibintoc]     % bibliography  in toc
https://www.sharelatex.com/blog/2013/07/31/getting-started-with-biblatex.html
\usepackage[hyperref=true,
            url=false,
            isbn=false,
            backref=true,
            style=custom-numeric-comp,
            citereset=chapter,
            maxcitenames=3,
            maxbibnames=100,
\usepackage[style=authoryear,autocite=footnote]{biblatex}
            block=none]{biblatex}
\usepackage[hyperref=true,
            url=false,
            isbn=false,
            backref=true,
            style=custom-numeric-comp,
            citereset=chapter,
            maxcitenames=3,
            maxbibnames=100,
            block=none]{biblatex}
http://tex.stackexchange.com/questions/5091/what-to-do-to-switch-to-biblatex
http://www.khirevich.com/latex/bibliography/
http://www.khirevich.com/latex/biblatex/
backref=true

% backref=false
\DefineBibliographyStrings{english}{%
    backrefpage  = {see p.}, % for single page number
    backrefpages = {see pp.} % for multiple page numbers
}
\usepackage[style=authoryear,sorting=ynt]{biblatex}
This would use the author-year style and then sort the bibliography entries by year, name, title. Here’s a list of some of the different sorting options available:

nty - Sorts entries by name, title, year.

nyt - Sorts entries by name, year, title.

nyvt - Sorts entries by name, year, volume, title.

anyt - Sorts entries by alphabetic label, name, year, title.

anyvt - Sorts entries by alphabetic label, name, year, volume, title.

ynt - Sorts entries by year, name, title.

ydnt - Sorts entries by year (descending order), name, title.

none - No sorting. Entries appear in the order they appear in the text.

If you don’t specify an order the default is nty.


\cite - the most basic one. Prints without any brackets except when using the alphabetic or numeric style when it uses square brackets.

\parencite - prints citations in parentheses except when using the alphabetic or numeric style when it uses square brackets.

\footcite - puts the citation in a footnote.
* Subdividing Bibliographies

One of the nice things about biblatex is that you can subdivide bibliographies according to source type. Here’s an example of subdividing by source type:

\printbibheading
\printbibliography[type=book,heading=subbibliography,title={Book Sources}]
\printbibliography[nottype=book,heading=subbibliography,title={Other Sources}

\printbibheading
\printbibliography[keyword=major,heading=subbibliography,title={Major Sources}]
\printbibliography[keyword=minor,heading=subbibliography,title={Minor Sources}]
Note that I used \autocite instead of \parencite which is the actual counterpart of natbib's \citep. \autocite is a high-level citation command that will be translated into the low-level bare citation command appropriate for the chosen style - e.g. it will enclose a citation in parentheses in authoryear styles, but produce a footnote citation in authortitle styles. Even more, it will automatically move trailing punctuation.
http://tex.stackexchange.com/questions/5091/what-to-do-to-switch-to-biblatex

For some of the custom (not already built-in) biblatex styles, additional preamble adjustments may be advisable - see the example provided by Seamus for biblatex-apa.

As Simon Byrne has mentioned: If you don't want to change every instance of \citep and \citet in every document to its biblatex counterpart, use the natbib=true compatibility option.

Typically, you'll select one or several local .bib files as your bibliographic database; however, \addbibresource also allows to load remote resources and other data types (e.g., ris).

.bib file

domwass has already mentioned that changes to your .bib files are not mandatory, but you'll miss some of the goodies offered by biblatex. When I switched to biblatex, I changed my address fields to location and my journal fields to journaltitle. I also added hyphenation fields in order to be able to switch languages on a per-entry basis in the bibliography.

Biber

biblatex will work for the most part with traditional BibTeX and its 8-bit version bibtex8, but I recommend the use of Biber (the default backend since biblatex v2.0) for the following reasons:

Full unicode support.

No capacity issues. (In contrast, when using BibTeX with bibliographies of about one hundred entries, I've run into errors disguised as obscure warnings - see section 2.4.2 of the biblatex manual for details.)

Multiple or subdivided bibliographies will always be processed in a single pass.

Many biblatex features introduced since v1.1 (e.g., advanced name disambiguation, smart crossref data inheritance, configurable sorting schemes, dynamic datasource modification) are "Biber only".

Biber is included in TeXLive and MiKTeX; latexmk also supports the use of Biber.

apalikeThe NATBIB Citation commands
The natbib package defines a number of very useful citation commands which replace the usual \cite. These are really necessary in any author-year citation system, where you don't always cite a reference using the same format for the citation. These commands and their output are illustrated below. The most frequently used are \citet (textual cite) and \citep (parenthetical cite). \cite is equivalent to \citet, but this shouldn't be used because it is often defined by other style files.
\citet{KEY}
Bester et al. (1998)
\citep{KEY}
(Bester et al. 1998)
Multiple citations work within a single cite, for example
\citep{KEY1, KEY2, KEY3, KEY4, ...}
(Bester et al. 1998; Garibaldi et al. 1997, 1998a,b; ...)
The lettering of the citations and references is done automatically.
You can use optional arguments to get text before and after the citation(s):
\citep[hereafter B98]{KEY}
(Bester et al. 1998, hereafter B98)
\citep[e.g.,][]{KEY}
(e.g., Bester et al. 1998)
\citep[see][p. 68]{KEY}
(see Bester et al. 1998, p. 68)
Any of these can have a * affixed to make a full author list when "et al." would normally be used, e.g.,
\citet*{KEY}
Bester, Winters, & Alexander (1998)
Note that the nat2jour.pl script takes care of the bizarre practice of listing three names on the first citation and using "et al." thereafter, so you don't need to worry about that, although the intermediate file will come out "wrong".
\citeauthor{KEY}
Bester et al.
\citeyear{KEY}
1998
\citeyearpar{KEY}
(1998)
\citealp and \citealt are the sames as \citep and \citet, respectively, except that they do not produce any parentheses at all:
\citealt{KEY}
Bester et al. 1998
Finally, \citetext can be used to place arbitrary text around a citation. Look at the comments in the natbib style files for more information.

 
 
Options for NATBIB
usepackage[options]{natbib} 
 

 
round
(default) for round parentheses;
square
for square brackets;
curly
for curly braces;
angle
for angle brackets;
colon
(default) to separate multiple citations with colons;
comma
to use commas as separators;
authoryear
(default) for author­year citations;
numbers
for numerical citations;
super
for superscripted numerical citations, as in Nature;
sort
orders multiple citations into the sequence in which they appear in the list of references;
sort&compress as sort but in addition multiple numerical citations are compressed if possible (as 3­6, 15);
longnamesfirst makes the first citation of any reference the equivalent of the starred variant (full author list) and subsequent citations normal (abbreviated list); 
 
 
Usage
Just include the package natbib with the proper options before \begin{document} like 
 
 
\documentclass[11pt]{psuthesis} 
..... 
%% optional packages, in case you want AMS math macros and AMS symbols
\usepackage[comma,authoryear]{natbib} %% Here goes the natbib declaration ( Other options can be given) 
.... 
 

  
 
\begin{document}
...
citet{KEY}
%% Citatitions
\citep{KEY}
...

 
 
\bibliographystyle{ieeetr} 
% or: plain,unsrt,alpha,abbrv,acm,apalike,...
\bibliography{abbr_long,pubext} 
...
\end{document} 
 
  
 
 
Useful websites for Natbib Help 
 
 
http://www.tug.org.in/tutorial/chap10-prn.pdf
http://www.linmpi.mpg.de/english/services/software/latex/localtex/doc/natbib.pdf 
 

(You are possibly referring to my answer to What to do to switch to biblatex?)

For citations that aren't used in the flow of the text ("As Einstein (1905) showed ...", produced by \textcite), biblatex offers four basic citation commands resp. package options:

\cite [autocite=plain]: Citations are typeset as-is;

\parencite [autocite=inline]: Citations are typeset in parentheses;

\footcite [autocite=footnote]: Citations are typeset as footnotes;

\supercite [autocite=superscript] (only available for the numeric style family): Citations are typeset as superscripts.

Instead of choosing one of those four commands, one may simply use the higer-level command \autocite; biblatex will automatically translate it into the lower-level citation command most appropriate for the style family (e.g., \parencite for authoryear, \footcite for authortitle).

If you want to switch to a non-default citation command (e.g., \footnote for authoryear), you simply add the corresponding package option:

\usepackage[style=authoryear,autocite=footnote]{biblatex} 
* New style
%%%% Get plainat.bst
\usepackage[style=authoryear-comp,firstinits=true,citestyle=authoryear,natbib=true,backend=bibtex]{biblatex}
\renewcommand\nameyeardelim{, }
\DeclareNameAlias{sortname}{last-first}
\renewcommand*{\multinamedelim}{\addcomma\space}
\renewcommand*{\finalnamedelim}{\addcomma\space}
\setlength{\bibitemsep}{\baselineskip}
\renewbibmacro{in:}{}
